name: akademik_app
description: A Flutter academic app with courses and attendance
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Backend
  supabase_flutter: ^2.6.0

  # Charts
  fl_chart: ^0.66.2

  # Date formatting (DateFormat)
  intl: ^0.19.0

  # UI font (optional)
  google_fonts: ^6.2.1

  # Swipe actions (Slidable) - buat edit/hapus list
  flutter_slidable: ^3.1.0

  # CSV export
  csv: ^6.0.0

  # Share file (Share.shareXFiles, XFile)
  share_plus: ^10.0.0

  # File path (getApplicationDocumentsDirectory)
  path_provider: ^2.1.4

  # PDF export (pw.Document)
  pdf: ^3.11.0
  printing: ^5.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
